### ISSUE TITLE
Deprecation errors

### ISSUE THREAD

**Issue by elfacht** [hillholliday/Craft-User-Manual#10]
Following deprecation errors are occuring:

_Looping through element queries directly has been deprecated. Use the all() function to fetch the query results before looping over them._  
`/Users/…/vendor/hillholliday/craft-user-manual/src/templates/index.twig:15`

_craft.request.getLastSegment() has been deprecated. Use craft.app.request.segments|last instead._  
`/Users/…/vendor/hillholliday/craft-user-manual/src/templates/index.twig:16`

_craft.config.get() has been deprecated. Use craft.app.config.general.setting instead._  
`/Users/…/vendor/hillholliday/craft-user-manual/src/templates/settings.twig:26`

_craft.config.get() has been deprecated. Use craft.app.config.general.setting instead._  
`/Users/…/vendor/hillholliday/craft-user-manual/src/templates/settings.twig:41`

_craft.config.get() has been deprecated. Use craft.app.config.general.setting instead._  
`/Users/…/vendor/hillholliday/craft-user-manual/src/templates/settings.twig:60`

**Comment by mcclaskiem** [comment]
@elfacht Will work on switching over our templates to use the new Craft 3 Syntax for next release, thanks for tracking this!
