### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by darylknight** [hillholliday/Craft-User-Manual#13]
Thanks for porting it to Craft 3! There are several deprecation warnings showing in the CP for this plugin.

![image](https://user-images.githubusercontent.com/1250017/49701439-1e607f80-fbf5-11e8-870b-f7176bf1da81.png)

**Comment by RobErskine** [comment]
hey @darylknight. Thanks for logging this; has been on our backlog for awhile. Let us tackle this weekend before the holiday hits and we'll issue a new release.

**Comment by laurabennett** [comment]
craft.config.get() has been deprecated. Use craft.app.config.general.setting instead.

**Comment by RobErskine** [comment]
Happy holidays @darylknight! Can you let me know what version you're on? I think we resolved these in a previous release. I'm not getting any warnings on v2.0.1. ![no dep warnings](https://cl.ly/09dc4095e5e7/Screen%20Shot%202018-12-24%20at%2012.11.10%20PM.jpg)

**Comment by darylknight** [comment]
Thanks Rob - yeah, I'm not seeing these anymore either after updating.
