### ISSUE TITLE
Failed to instantiate component or class UserManualAsset

### ISSUE THREAD

**Issue by kblizeck** [hillholliday/Craft-User-Manual#16]
Craft 3 install, using the `project.yaml` setup. On local my UserManual works great, but on both development and production servers, I get the following error when trying to visit the UserManual to view the pages - editing them works as expected.

`Failed to instantiate component or class "hillholliday\usermanual\assetbundles\usermanual\UserManualAsset".`

![Screen Shot 2019-10-28 at 9 31 07 AM](https://user-images.githubusercontent.com/9886123/67692601-ffcaba80-f965-11e9-8636-04d75538e3bd.png)

Clearing cache doesn't trigger anything. Any ideas on a fix?

**Comment by RobErskine** [comment]
Hey @kblizeck. I don't know that we've tested this using the [new project.yaml](https://docs.craftcms.com/v3/project-config.html) set up. I'll have to try to give that a shot. It's odd that it's working locally, but not on any of your remote envs; but I guess that's the point of the project.yaml set up.

While I look into this, can you try the following?
- deleting your `storage/` directory, and recreating it?
- try doing a `composer update` on your staging environment to see if that initializes the component?

**Comment by kblizeck** [comment]
Hi @RobErskine Running the `composer update` worked! It needed reinitialization. Thank you for the assist!
