### ISSUE TITLE
Does not show up in plugin list on case-sensitive environments

### ISSUE THREAD

**Issue by aaronbushnell** [hillholliday/Craft-User-Manual#2]
I've tried to install this plugin on a case-sensitive Apache environment, but it won't show up in the list of available plugins. I thought renaming "UserManual" to "usermanual" would work, but that did not seem to fix the issue either.

**Comment by aaronbushnell** [comment]
False alarm, changing it to "usermanual" did work! My environment must have had the old "UserManual" still when I tried. :smile:

**Comment by RobErskine** [comment]
Thanks for the update @aaronbushnell! We should still certainly rename it to conform to Craft best practices, though.

**Comment by RobErskine** [comment]
Should be all set, fixed with  https://github.com/hillholliday/Craft-User-Manual/commit/720b24027a821ae22f3873d8132d3d739398f9ba. Thanks!

**Comment by aaronbushnell** [comment]
Ah, thanks a bunch @RobErskine! One note: I think the README still references the `UserManual` version instead of `usermanual`. Other than that it's great!
