### ISSUE TITLE
Users Can't Scroll Down

### ISSUE THREAD

**Issue by BrandonCronk** [hillholliday/Craft-User-Manual#25]
I have checked in Chrome, Firefox, & Safari on a Mac. I can't scroll down to view long guide pages. We are using the default template and just have the one rich text variable called "body." We can scroll down on when editing the guide pages but can't scroll down when viewing them as the content editors would be doing.

**Comment by RobErskine** [comment]
This should be resolved by #24 and installed with 2.1.1.

**Comment by laurabennett** [comment]
This does work with 2.1.1 but I had to install with composer, it didn't show up in Craft updates.

**Comment by paul-frost** [comment]
I had same problem and 2.1.1 isn't getting picked up as an update in the control panel.
