### ISSUE TITLE
⚠️ Please read: existing trouble, January 2022

### ISSUE THREAD

**Issue by RobErskine** [hillholliday/Craft-User-Manual#26]
Hey there,

I originally launched this plugin as open-source and I intend to keep it that way. Unfortunately I left my role at my previous job where I released this project. I am working with Pixel & Tonic to resolve the namespace issues across ID management and desire to provide continued support long-term. If there are any hiccups or issues you encounter implementing this plugin please let me know.

Thanks,
Rob

**Comment by khalwat** [comment]
This plugin is published on packagist as `hillholliday/craft-user-manual` -> https://packagist.org/packages/hillholliday/craft-user-manual but what is listed on the plugin store and in the GitHub repo is `roberskine/craft-user-manual` -- looks like it's published incorrectly on packagist, or the meta info on the plugin store & docs hasn't been updated to match https://plugins.craftcms.com/usermanual 

Either the Craft plugin store & arguably the GitHub repo & docs should be changed to `hillholliday/craft-user-manual` or it should be published to Packagist as `roberskine/craft-user-manual`

**Comment by angrybrad** [comment]
I was able to install the plugin fine from the Plugin Store.

I think the only issue here is on the Packagist side. They don't have a way to rename something once it's been submitted, so @RobErskine you'd need to submit a new one using https://packagist.org/packages/roberskine/craft-user-manual and mark the old one as abandoned while pointing people to the new one. That should fix it so people trying to install/update outside the context of Craft (using Composer) will work.

**Comment by Kashkin** [comment]
@RobErskine, any update on this? I'l having the issue Brad mentioned of not being able to update using Composer.

**Comment by RobErskine** [comment]
@angrybrad @khalwat @Kashkin 

Thank you all for looking into this issue. I've been swamped at work but will be able to look into it for sure over the next few days.

On top of that I'm excited to prepare this for the Craft 4 launch as well as work on some long-asked for feature requests.

**Comment by CreateSean** [comment]
if we're using the old hillholiday version is it safe to just rename the package in composer.json?

**Comment by animaux** [comment]
> if we're using the old hillholiday version is it safe to just rename the package in composer.json?

I was able to update Craft via composer after adding the following in crafts root `composer.json` before `"require"`:

``` json
   "repositories": [
     {
       "type": "git",
       "url": "git@github.com:RobErskine/Craft-User-Manual.git"
     }
   ],
```

EDIT: After authorising my github account, I had to follow the brute force method listed here —> https://nono.ma/github-oauth-token-for-github-com-contains-invalid-characters-on-composer-install

**Comment by RobErskine** [comment]
I've gone ahead and updated the documentation to [use the correct Packagist org](https://packagist.org/packages/hillholliday/craft-user-manual).

You should be able to install through the Plugin store (yourwebsite.nitro/admin/plugin-store/usermanual/changelog) or through composer `composer require hillholliday/craft-user-manual`
