### ISSUE TITLE
Port to Craft 4

### ISSUE THREAD

**Issue by RobErskine** [hillholliday/Craft-User-Manual#28]
Creating a ticket to prepare this plugin for Craft 4.

Going to try to work on this the week of 2022-05-02.

**Comment by animaux** [comment]
Any progress on this? :)

**Comment by RobErskine** [comment]
@animaux Not yet... but I appreciate the bump! 

I am going to try to get this out this week! If anyone wants to take a look a the `craft4` branch, I've started the process [outlined in the docs](https://craftcms.com/docs/4.x/extend/updating-plugins.html) but it crashes on install. Outside of that I haven't had time to take a look. Hopefully this week!

**Comment by animaux** [comment]
Many thanks!

**Comment by animaux** [comment]
Here’s your weekly bump `;)`.

(Really sorry for nagging, but this extension is the single last obstacle in updating to Craft 4 for one of your sites.)

**Comment by HalCodes** [comment]
I would like to also chime in to say that the present lack of Craft 4 support is making us look at other options.  Hopefully this can be supported soon!  Thank you for all your hard work on this.

**Comment by CreateSean** [comment]
Also eager to see this in Craft 4

**Comment by animaux** [comment]
Anything we could do to help?

**Comment by RobErskine** [comment]
Craft 4 release is out the door! Thanks to @Chris-DuCharme for his work in [PR#29](https://github.com/RobErskine/Craft-User-Manual/pull/29) for supporting the Craft 4 release.

![Craft User Manual 4 in the Craft app store](https://p198.p4.n0.cdn.getcloudapp.com/items/nOuXlWpy/737f7f5e-f21e-4ed0-9a8f-3641e2a22d7c.jpeg?source=viewer&v=098bdedd39a526d29b65e34d2daaaaaf)
