### ISSUE TITLE
Plugin causes "Twig instantiated before Craft is fully initialized" warning

### ISSUE THREAD

**Issue by FlorisDerks** [hillholliday/Craft-User-Manual#32]
When I enable this plugin in Craft CMS v4.2.0.2 I get to see warnings telling me that Twig is instantiated too early (in the ./storage/logs/ directory or on the commandline when CRAFT_STREAM_LOG is active):

`2022-08-03 11:32:08 [console.WARNING] [craft\web\View::createTwig] Twig instantiated before Craft is fully initialized. {"memory":22820336} `

This seemed to be caused by the `_addTwigExtensions()` function that is called from the init-function in UserManual.php. This uses `Craft::$app->view->twig->addExtension(new UserManualTwigExtension);`, but according to https://craftcms.com/docs/4.x/extend/extending-twig.html#register-a-twig-extension should be `Craft::$app->view->registerTwigExtension(new UserManualTwigExtension);`

Would it be possible to fix this warning?

**Comment by RobErskine** [comment]
This has been addressed in 5.0.2!
