### ISSUE TITLE
Feature request: add structure level indicator to admin

### ISSUE THREAD

**Issue by daltonrooney** [hillholliday/Craft-User-Manual#36]
When using a structure as a source for the user manual, it would be nice to have a visual indicator of hierarchy for nested pages. Here's an example:

<img width="226" alt="user-manual-structure" src="https://user-images.githubusercontent.com/742045/211430327-df688dd8-3696-442e-9fc2-a0c57ddb792e.png">

I have a pull request incoming which implements this.

**Comment by chadcrowell** [comment]
+1

**Comment by RobErskine** [comment]
This should be included now in the plugin: 
![Arc-Personal_2024-07-31 at 16 09@2x](https://github.com/user-attachments/assets/66b3106b-8be8-4521-bf82-0d7942b00728)
