### ISSUE TITLE
Craft 4 Update Versioning Issue in the Read Me

### ISSUE THREAD

**Issue by sjstark** [hillholliday/Craft-User-Manual#38]
Appreciate all of your work! Pretty minor lil issue, but saw in a recent change that you updated it to `hillholliday/craft-user-manual: 2.1.2` but I believe it should actually be `hillholliday/craft-user-manual: 4.0.0` so the `composer.json` file shows `"hillholliday/craft-user-manual": "^4.0.0",`

**Comment by RobErskine** [comment]
Should be resolved!
