### ISSUE TITLE
Craft 5 version needs registerTwigExtension instead of addExtension

### ISSUE THREAD

**Issue by mike-moreau** [hillholliday/Craft-User-Manual#45]
Hey there,

I noticed that with the Craft 5 version of User Manual there is a lingering issue that occurred in the Craft 4 version also.

In the main plugin file, the twig extension needs to be added in this way:
```php
private function _addTwigExtensions(): void
    {
        Craft::$app->view->registerTwigExtension(new UserManualTwigExtension);
    }
```

This would resolved a few related issues too:
- https://github.com/RobErskine/Craft-User-Manual/issues/32
- https://github.com/RobErskine/Craft-User-Manual/pull/33

@RobErskine could you roll in this fix when it's convenient?

**Comment by RobErskine** [comment]
hey @mike-moreau thanks for bringing this to my attention. I just dropped a new release (https://github.com/RobErskine/Craft-User-Manual/releases/tag/5.0.2) that has this fix! Let me know if there is anything else I can take a look at.

**Comment by mike-moreau** [comment]
Thank you!
