### ISSUE TITLE
Can't install using ddev command

### ISSUE THREAD

**Issue by AmandaLutzTO** [hillholliday/Craft-User-Manual#46]
On Craft Team 5.3.6. Trying to install this plugin using ddev instructions:

$ ddev composer require "roberskine/craft-user-manual:^5.0.2" -w && ddev craft plugin/install usermanual
./composer.json has been updated
Running composer update roberskine/craft-user-manual --with-dependencies
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires roberskine/craft-user-manual, it could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
Composer [require roberskine/craft-user-manual:^5.0.2 -w] failed, composer command failed: exit status 2. stderr=

**Comment by RobErskine** [comment]
Hi there @AmandaLutzTO; thanks for logging this issue. Instead of `roberskine/craft-user-manual` can you use `hillholliday/craft-user-manual`? I worked on this plugin while working at my last outfit and when I left I couldn't move it over. Let me know if that works and I'll take a look at updating the documentation.

**Comment by AmandaLutzTO** [comment]
Yup that worked. Thanks!

**Comment by RobErskine** [comment]
Great, @AmandaLutzTO! Can I ask where you saw these `ddev instructions`? 
> On Craft Team 5.3.6. Trying to install this plugin using ddev instructions:

I want to update the documentation anywhere the old way to install the plugin were referenced, but I'm not sure where those instructions are?

**Comment by AmandaLutzTO** [comment]
The Craft 5 cp Plugin Store 
![image](https://github.com/user-attachments/assets/1292d6fb-c0d0-4d35-8f58-29bb9e9135a9)
