### ISSUE TITLE
Update readme on how to setup Section

### ISSUE THREAD

**Issue by tiborsaas** [hillholliday/Craft-User-Manual#6]
Hello,

I'm having trouble with setting up the section propery. What URL does it expect? First entry is displayed correctly, but in the navigation, any other link throws a 404 page no matter what level I move it to.

**Comment by RobErskine** [comment]
Hey @tiborsaas, could you link how you have your entry urls set up?

**Comment by tiborsaas** [comment]
I have no idea what happened, the section I created was having trouble saving entries, it started to throw failed tasks. I deleted it, picked a different handle and it now works fine. 

#xfiles

**Comment by RobErskine** [comment]
@tiborsaas #spooky https://www.youtube.com/watch?v=hdl9Byw3ej8

Let us know if it happens again and you can reproduce.

**Comment by tiborsaas** [comment]
LOL 

Actually I just caught it again. If the slug has a non-ascii character in it, for example "kezelések" it won't load.

**Comment by RobErskine** [comment]
@tiborsaas I've just pushed an update that will fix this for basic non-ascii characters (é,å,ñ, etc). The regex isn't perfect, but I'll improve it over time. Fixed in [b160d622].(https://github.com/hillholliday/Craft-User-Manual/commit/b160d6229debfd60302ef54b9abdf1401ec2bb4d)
