### ISSUE TITLE
Plans for Craft 3?

### ISSUE THREAD

**Issue by timkelty** [hillholliday/Craft-User-Manual#7]
Interested if you have plans to port this to Craft 3.

There is https://github.com/wbrowar/craft-3-guide, but that takes quite a different, template-based approach.

**Comment by RobErskine** [comment]
Hey Tim. Haven't put a lot of time into it since RC1. Might be a good exercise for us to explore as we're now on RC14 I believe. I'll look into it this weekend.

**Comment by timkelty** [comment]
Sounds good - happy to lend a hand as well.

**Comment by jsunsawyer** [comment]
Also interested in this. Worked great on my last Craft 2 project. Saw the Guide plugin that @timkelty mentioned. Prefer the simplicity of yours.

**Comment by jcdarwin** [comment]
[PR is now](https://github.com/hillholliday/Craft-User-Manual/pull/8) up for the Craft3 version of the UserManual plugin.

I look forward to being able to use this repository rather than my own fork once it's merged.

**Comment by dgrigg** [comment]
Is this getting merged? Would love to have it working in Craft 3

**Comment by RobErskine** [comment]
Sorry ya'll. Was doing testing on our end. This has now been merged and is up on [master](https://github.com/hillholliday/Craft-User-Manual/tree/master)! Folks looking for the Craft 2 version can find it on the `craft2` [branch](https://github.com/hillholliday/Craft-User-Manual/tree/craft2).

Thanks again to @jcdarwin and all his work for getting this up on Craft 3. It's very much appreciated.
