### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by mannachurch** [hillholliday/Craft-User-Manual#9]
I'm getting a `Composer was unable to install the updates due to a dependency conflict.` when trying to install your plugin.

`Composer output: Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

Problem 1
- The requested package hillholliday/craft-user-manual could not be found in any version, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
see for more details.
- It's a private package and you forgot to add a custom repository to find it

Read for further common problems.
Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.`

**Comment by mcclaskiem** [comment]
@mannachurch Could you provide a snippet of your composer file for this plug-in to see how you have it set up. Thanks!

**Comment by elfacht** [comment]
Same error here.

using: `composer require hillholliday/craft-user-manual`

composer.json:

`"hillholliday/craft-user-manual": "^2.0"`

but it disappears during installation process.

**Comment by elfacht** [comment]
Well, another plugin interrupted the process. Everything's fine now.

**Comment by chadcrowell** [comment]
Same exact issue as mannachurch above. Can't install. Using plugin store install button. Craft CMS 3.0.24 all other plugins up to date.

**Comment by mcclaskiem** [comment]
@mannachurch @chadcrowell Just a quick update: 

I was able to install the plugin directly via composer. Based on that, I think it is an issue with how the plugin is registered with the Craft plug-in store. If you could install manually via composer temporarily I will update this issue once the plugin store has been updated and is working correctly. 

Thanks!

**Comment by mcclaskiem** [comment]
@mannachurch @chadcrowell Another update! I just updated the plugin store listing to have an all lower case package name and it worked for me installing via the store. Closing this issue now as it seems to be resolved but please re-open if you experience the same error. Thanks!
